sudo: required

services:
  - docker

before_install:
  - docker build -t mskhan-devops/docker-react -f Dockerfile.dev .

script:
  - docker run mskhan-devops/docker-react npm run test -- --coverage
  